baseURL: "http://52etf.net/"
languageCode: "zh-cn"
title: "我爱ETF"
theme: "hugonews"

paginate: 50

permalinks:
  /: /:year/:month/:section/:filename/
summaryLength: 100
hasCJKLanguage: true

related:
  threshold: 80
  includeNewer: false
  toLower: false
  indices:
  - name: tags
    weight: 100
  - name: date
    weight: 10

menu:
  main:
  - identifier: 'tools'
    name: 量化工具
    #pre: <i class="fa fa-magic" aria-hidden="true"></i>
    url: /tools/
    weight: -110
  - name: 关于
    #pre: <i class="fa fa-user-circle-o" aria-hidden="true"></i>
    url: /about/
    weight: -80
  - name: 博客
    #pre: <i class="fa fa-user-circle-o" aria-hidden="true"></i>
    url: "/blog/"
    weight: -90    
  - name: Tags
    #pre: <i class="fa fa-user-circle-o" aria-hidden="true"></i>
    url: /tags/
    weight: -95
  - identifier: 'books'
    name: 书单
    #pre: <i class="fa fa-book" aria-hidden="true"></i>
    url: /books/
    weight: -150
  - name: 精品基金
    #pre: <i class="fa fa-diamond" aria-hidden="true"></i>
    url: /funds/
    weight: -140
  - name: 长赢
    #pre: <i class="fa fa-pie-chart" aria-hidden="true"></i>
    url: /policies/
    weight: -180
  - identifier: 'news'    
    name: 文摘
    #pre: <i class="fa fa-globe" aria-hidden="true"></i>
    url: /news/
    weight: -190
  - identifier: 'dash'
    name: 仪表盘
    #pre: <i class='fa fa-tachometer'></i>
    url: /dash/
    weight: -200